### ISSUE TITLE
Fix compliance of tagpacks

### ISSUE THREAD

**Issue by wincentbalin** [INTERPOL-Innovation-Centre/TagPackConverters#26]
Validation checks with [tagpack tool](https://github.com/graphsense/graphsense-tagpack-tool) have shown compliance issues, mostly date format in the `lastmod` entry, in many tagpacks generated in this repository.

**Comment by wincentbalin** [comment]
Add `abuse: extremism` to the SPLC-CR tagpack entries.

**Comment by wincentbalin** [comment]
The `datetime` filed type in the tagpack YAML format corresponds to the `datetime.date` type in Python: https://github.com/graphsense/graphsense-tagpack-tool/blob/master/tagpack/tagpack_schema.py#L76

**Comment by behas** [comment]
Is this still an issue? @wincentbalin could you provide an example? I'll then file an issue at https://github.com/graphsense/graphsense-tagpack-tool/issues

**Comment by wincentbalin** [comment]
Running `python bin/tagpack-tool validate ../TagPackConverters/EtherScanDB/etherscamdb_tagpack.yaml` to validate the EtherScan DB tagpack in the TagPackConverters repository yields this result:

```sh
========================== TagPack validation starts ===========================
Path: ../TagPackConverters/EtherScanDB/etherscamdb_tagpack.yaml
Loaded taxonomies: ['abuse', 'entity']
Loaded schema: tagpack_schema.yaml
Collected 1 TagPack files

../TagPackConverters/EtherScanDB/etherscamdb_tagpack.yaml: FAILED
Schema Validation Error: Field lastmod must be of type datetime
========================= 0/1 TagPacks passed in 2.29s =========================
```

Running `grep lastmod ../TagPackConverters/EtherScanDB/etherscamdb_tagpack.yaml` to show the culprint line yields

```sh
lastmod: '2019-07-18'
```

**Comment by behas** [comment]
I filed an issue here: https://github.com/graphsense/graphsense-tagpack-tool/issues/69

...and will discuss it in our team.

**Comment by wincentbalin** [comment]
This issue appears when saving a _date string_, such as `'2023-01-22'`, instead of using a _date_, like `2023-01-22`. The issue is easily fixed by replacing `datetime_variable.isoformat()` with `datetime_variable.date()` or even using `datetime_variable` as is.

Tested it with SPLC cryptocurrency tagpack converter, and it works. This fixes https://github.com/graphsense/graphsense-tagpack-tool/issues/69 too.

**Comment by VinceICPO** [comment]
I suppose this means we can close this issue since @wincentbalin found a fix above.
