### ISSUE TITLE
Add ChainAbuse

### ISSUE THREAD

**Issue by wincentbalin** [INTERPOL-Innovation-Centre/TagPackConverters#34]
The portal https://www.chainabuse.com/ contains quite a lot of interesting data. The bitcoinabuse.com portal links to one of their reports.

Both are registered by CloudFlare, but by different means (judging from WHOIS intofmation).

**Comment by VinceICPO** [comment]
This service belongs to TRM Labs. @wincentbalin, let me know if you need contacts :)

**Comment by behas** [comment]
I  contacted them already, but it seems that they are not willing to share the data they are collecting. Which, of course, contradicts the idea of "making things safer ***together***". Maybe @VinceICPO you know a direct contact.

**Comment by VinceICPO** [comment]
I guess it isn't "they are not willing" but more a "they are not able to". I should probably setup a meeting.
This might need to be a work topic for our next New Technology Forum in Munich 10-11 October.

**Comment by wincentbalin** [comment]
@VinceICPO, I started to write a scraper, but the website requres to login at the 10th page when going through the list of reports. Their API does not allow the retrieval of the complete database.

I think we should close this issue, because we will not get a meaningful amount of data. @VinceICPO, what do you think?

**Comment by VinceICPO** [comment]
Closing this for now, pending internal discussions with TRM Labs and relevant actors.
Anyone reviewing this from LEA, please contact INTERPOL for further details.
