### ISSUE TITLE
Issues with scraping the ScamSearch reports

### ISSUE THREAD

**Issue by VinceICPO** [INTERPOL-Innovation-Centre/TagPackConverters#5]
Scam Search is a repository of scams and their related details (emails, telephones, cryptocurrency addresses...).

Historical records are publicly available at:
https://scamsearch.io/view_report?page=1

**Comment by wincentbalin** [comment]
Is it really reliable? Quite a few cryptocurrency addresses from there, for example `12yeMijWZKioqyFmaZCser9mUNb5YeFFMg`, aren't recorded in the respective blockchain at all.

**Comment by VinceICPO** [comment]
That's a very valid question Wincent.
These tagpacks are only an indication and indeed the analyst always has to double check the facts before using them for evidential purposes.
With Scamsearch, basically anyone can report anything so we should indeed expect some non-reliable info and need to be extra cautious in checking the facts. This can be informed by lowering the "confidence score". Doc here: [GraphSense TagPacks](https://github.com/graphsense/graphsense-tagpacks)

**Comment by wincentbalin** [comment]
It seems that the cryptocurrency address reports start at the page 1 and stop (currently) at the [page 1282](https://scamsearch.io/view_report?page=1282). Should a scraper then stop at the first non-cryptocurrency-address pattern?

**Comment by VinceICPO** [comment]
It does look like this is when they started registering crypto-related scams. So yes should be safe to assume a scraper could stop when it hits the one report for BTC 35Nbao1*** on Tue, 21 Dec 2021 17:26:51.

**Comment by wincentbalin** [comment]
This feature was implemented in the pull request #15. However, there is an issue: the scraper exists on encountering the BTC address mentioned above. Should this address appear more recently (and hence appear in the report list before other addresses), this exit condition will have to be rewritten.

**Comment by wincentbalin** [comment]
Additionally, it is entirely possible that the new entries shift existing entries to the following pages in the list and the scraper will overlook these entries, if it jumps to the previous page at the same time or later.

**Comment by wincentbalin** [comment]
I suggest to count consecutive pages without BTC addresses and to exit after the count of such pages goes over the threshold of, say, 10 pages.

**Comment by VinceICPO** [comment]
> I suggest to count consecutive pages without BTC addresses and to exit after the count of such pages goes over the threshold of, say, 10 pages.

Yes sounds like a best-effort measure which would work. The trick will be to find the right threshold and guess-testing isn't exactly practical...
