### ISSUE TITLE
Add Faucet services ?

### ISSUE THREAD

**Issue by VinceICPO** [INTERPOL-Innovation-Centre/TagPackConverters#6]
This is somewhat different to Sanctions lists and relates to Faucets (getting paid in crypto for watching adverts or playing games).
Here is a list of such services:
https://www.cryptoblacklist.io/en/paying-crypto-faucets/

And here is an example of where the actual transactions and addresses are displayed:
https://www.coinpayu.com/payment

**Comment by wincentbalin** [comment]
It seems that the only faucet from the first link above providing a list of transactions or addresses (apart from Coinpayu) is Pipeflare (https://pipeflare.io/transactions and https://pipeflare.io/game/leaderboard).

**Comment by wincentbalin** [comment]
Both _CoinPayU_ and _PipeFlare_ tagpack generators are implemented. As there are no other faucet services to scrape, I consider this issue as solved.

**Comment by VinceICPO** [comment]
Sure, we may close the issue, thank you.
